site_name: Triply Documentation
plugins:
  - search
  - mermaid2

nav:
  - Home: index.md
  - TriplyDB:
      - Getting started: triply-db-getting-started
  - TriplyETL:
      - Generics:
          - Overview: triply-etl
          - Getting started: triply-etl/getting-started
          - Command Line Interface (CLI): triply-etl/cli
          - Changelog: triply-etl/changelog
          - Declare: triply-etl/declare
          - Control: triply-etl/control
          - Debug: triply-etl/debug
          - Maintenance: triply-etl/maintenance
      - Approach:
          - Extract: 
              - Overview: triply-etl/extract
              - Formats: triply-etl/extract/formats
              - Record: triply-etl/extract/record
              - Types: triply-etl/extract/types
          - Transform:
              - Overview: triply-etl/transform
              - RATT: triply-etl/transform/ratt
          - Assert: 
              - Overview: triply-etl/assert
              - JSON-LD: triply-etl/assert/json-ld
              - Ratt: triply-etl/assert/ratt
          - Enrich: 
              - Overview: triply-etl/enrich
              - SHACL: triply-etl/enrich/shacl
              - SPARQL: triply-etl/enrich/sparql
          - Validate: 
              - Overview: triply-etl/validate
              - Graph comparison: triply-etl/validate/graph-comparison
              - SHACL: triply-etl/validate/shacl
          - Publish: triply-etl/publish
  - Yasgui:
      - Introduction: yasgui
theme:
  name: readthedocs
  locale: en

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  # - pymdownx.superfences:
  #       custom_fences:
  #         - name: mermaid
  #           class: mermaid
  #           format: !!python/name:pymdownx.superfences.fence_code_format
